### ISSUE TITLE
Update GitHub description 

### ISSUE THREAD

**Issue by carlocorradini** [karljj1/kdis#16]
Update GitHub description from:

> About
DIS(IEEE 1278.1) Fully Implemented in C++. A complete open source implementation of DIS (Distributed Interactive Simulation) in C++. 1278.1 and 1278.1a are fully implemented including enumerations. Includes several utility classes to help with developing your DIS app.

To:

> Open source implementation of DIS (Distributed Interactive Simulation) IEEE 1278.1

**Comment by carlocorradini** [comment]
![image](https://github.com/karljj1/kdis/assets/21266147/298186f8-8ff2-44fc-b649-301ae0f8f98c)

@karljj1 Add more tags (e.g. `dis`, `cpp`, etc...)

Thanks @karljj1

**Comment by karljj1** [comment]
Any suggestions? I added some extra tags.

**Comment by carlocorradini** [comment]
Put `kdis` also :)
