### ISSUE TITLE
chore: move sources to root

### ISSUE THREAD

**Issue by carlocorradini** [karljj1/kdis#6]
Can we move everything from the KIDS directory to the root? 
This results in a more uniform project structure overall, as well as the simplification of other "auto-tools" like [CPM](https://github.com/cpm-cmake/CPM.cmake).

**Comment by karljj1** [comment]
Im happy to take a PR to do this, otherwise I'm not sure I will be able to find the time.

**Comment by carlocorradini** [comment]
I'll create a PR 🥳
