### ISSUE TITLE
feat: Change from KDIS_SOURCE_DIR to CMAKE_CURRENT_SOURCE_DIR

### ISSUE THREAD

**Issue by carlocorradini** [karljj1/kdis#7]
The value of `KDIS_SOURCE_DIR` is not set and can cause UB. Moreover it can cause strange inclue errors while using"auto-tools" like [CPM](https://github.com/cpm-cmake/CPM.cmake).

From:
https://github.com/karljj1/kdis/blob/3cdfc0fb37872dbf070e43c77c7dfff8fa26a8a4/KDIS/CMakeLists.txt#L36
To:
```cmake
SET(BASE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/KDIS) 
```

**Comment by karljj1** [comment]
It's been a long time since I touched this, ill have to look through it and see what its purpose was. 
Im happy to take a PR to change it.

**Comment by carlocorradini** [comment]
I'll create a PR 🥳
